"""
Lambda Calibrator — Mathematical bridge between Elo-Poisson and external Odds.

Uses scipy.optimize to adjust Poisson lambdas (expected goals) so that the 
resulting 1x2 marginal probabilities of the Dixon-Coles matrix perfectly 
match the external market odds.
"""

import numpy as np
from scipy.optimize import minimize
from scipy.special import factorial

from src.model.poisson_model import dixon_coles_correction, get_1x2_from_matrix

def _loss_function(
    x: np.ndarray,
    target_1x2: tuple[float, float, float],
    prior_total_goals: float,
    w_total: float,
    rho: float,
    max_goals: int,
    target_over_25: float | None = None
) -> float:
    """
    Calculate Mean Squared Error between target 1x2 probs and the 
    matrix generated by lambdas x[0], x[1].
    """
    la, lb = x
    
    # Penalize negative lambdas
    if la <= 0 or lb <= 0:
        return 1000.0

    # Generate matrix directly using the existing function
    matrix = dixon_coles_correction(la, lb, rho, max_goals)
    
    # Normalize if slightly off
    total = np.sum(matrix)
    if total > 0:
        matrix = matrix / total
        
    p_h, p_d, p_a = get_1x2_from_matrix(matrix)
    
    # Target
    t_h, t_d, t_a = target_1x2
    
    # MSE loss for 1X2 marginals
    mse_1x2 = (p_h - t_h)**2 + (p_d - t_d)**2 + (p_a - t_a)**2
    
    w_1x2 = 1.0
    mse_total = 0.0
    w_tot_applied = 0.0
    
    if target_over_25 is not None:
        # Calculate Under 2.5 probability (x+y <= 2)
        p_under = (
            matrix[0, 0] + matrix[1, 0] + matrix[0, 1] + 
            matrix[1, 1] + matrix[2, 0] + matrix[0, 2]
        )
        p_over = 1.0 - p_under
        mse_total = (p_over - target_over_25)**2
        w_tot_applied = 1.0 # Strong weight because it's a market target
    else:
        # Total Goals Prior loss
        current_total_goals = la + lb
        mse_total = (current_total_goals - prior_total_goals)**2
        w_tot_applied = w_total
    
    # Add a tiny penalty to keep lambdas close to sensible bounds if multiple solutions exist
    l2_reg = 0.0001 * (la**2 + lb**2)
    
    return w_1x2 * mse_1x2 + w_tot_applied * mse_total + l2_reg


def calibrate_lambdas(
    target_1x2: tuple[float, float, float],
    initial_la: float,
    initial_lb: float,
    rho: float = -0.10,
    max_goals: int = 10,
    target_over_25: float | None = None,
) -> tuple[float, float]:
    """
    Calibrate Poisson lambdas to match target 1x2 odds.
    
    Args:
        target_1x2: (p_home, p_draw, p_away) from external odds.
        initial_la: Starting lambda for team A (from Elo).
        initial_lb: Starting lambda for team B (from Elo).
        rho: Dixon-Coles correlation parameter.
        
    Returns:
        (calibrated_la, calibrated_lb)
    """
    # Fallback bounds
    bounds = [(0.1, 8.0), (0.1, 8.0)]
    
    # Initial guess
    x0 = np.array([initial_la, initial_lb])
    
    prior_total_goals = initial_la + initial_lb
    
    t_h, t_d, t_a = target_1x2
    
    best_lambdas = None
    best_error = float('inf')
    
    # Grid search: try strongest prior first. If errors > 2.0 p.p., try weaker prior.
    # If target_over_25 is provided, we just use w=1.0 for the market and don't grid search.
    w_list = [0.10, 0.05, 0.02, 0.01, 0.00] if target_over_25 is None else [1.0]
    
    for w_total in w_list:
        result = minimize(
            fun=_loss_function,
            x0=x0,
            args=(target_1x2, prior_total_goals, w_total, rho, max_goals, target_over_25),
            method='L-BFGS-B',
            bounds=bounds,
            options={'ftol': 1e-6, 'disp': False}
        )
        
        if result.success:
            la_cal, lb_cal = float(result.x[0]), float(result.x[1])
            
            # Check thresholds
            mat = dixon_coles_correction(la_cal, lb_cal, rho, max_goals)
            mat = mat / np.sum(mat)
            p_h, p_d, p_a = get_1x2_from_matrix(mat)
            
            max_abs_error = max(abs(p_h - t_h), abs(p_d - t_d), abs(p_a - t_a))
            draw_error = abs(p_d - t_d)
            
            # If valid, return immediately (we start from strongest prior)
            if max_abs_error <= 0.02 and draw_error <= 0.02:
                return la_cal, lb_cal
                
            # Keep track of best just in case
            if max_abs_error < best_error:
                best_error = max_abs_error
                best_lambdas = (la_cal, lb_cal)
                
    # If optimization entirely fails or doesn't meet thresholds even at w=0.0
    if best_lambdas:
        print(f"    ⚠ Calibration threshold barely missed (Error: {best_error*100:.1f} p.p.). Using closest fit.")
        return best_lambdas
        
    print(f"    ⚠ Calibration failed for {target_1x2}. Using Elo lambdas.")
    return initial_la, initial_lb
